import { MateriaIconography } from "./types";
import {
  ArrowBackIcon,
  ArrowForwardIcon,
  CloseIcon,
  MenuIcon,
  CheckIcon,
  AddIcon,
  ChevronRightIcon,
  InfoRoundedIcon,
  ErrorIcon,
  DeleteIcon,
  HomeRoundedIcon,
  HomeOutlineRoundedIcon,
  SettingsRoundedIcon,
  SettingsOutlineRoundedIcon,
  InfoOutlineRoundedIcon,
} from "../../icons";

export const defaultMateriaIconography: MateriaIconography = {
  "arrow-back": ArrowBackIcon,
  "arrow-forward": ArrowForwardIcon,
  "close": CloseIcon,
  "menu": MenuIcon,
  "check": CheckIcon,
  "add": AddIcon,
  "chevron-right": ChevronRightIcon,
  "info-rounded": InfoRoundedIcon,
  "info-outline-rounded": InfoOutlineRoundedIcon,
  "home-rounded": HomeRoundedIcon,
  "home-outline-rounded": HomeOutlineRoundedIcon,
  "settings-rounded": SettingsRoundedIcon,
  "settings-outline-rounded": SettingsOutlineRoundedIcon,
  "error": ErrorIcon,
  "delete": DeleteIcon,
};
