import { MateriaIconography } from "./types";
import {
  ArrowBackRoundedIcon,
  ArrowForwardRoundedIcon,
  CloseRoundedIcon,
  MenuRoundedIcon,
  CheckRoundedIcon,
  AddRoundedIcon,
  ChevronRightRoundedIcon,
  InfoRoundedIcon,
  ErrorRoundedIcon,
  DeleteRoundedIcon,
  HomeRoundedIcon,
  HomeOutlineRoundedIcon,
  SettingsRoundedIcon,
  SettingsOutlineRoundedIcon,
  InfoOutlineRoundedIcon,
  LightModeRoundedIcon,
  DarkModeRoundedIcon,
  ContentCopyOutlineRoundedIcon,
} from "../../icons";

export const defaultMateriaIconography: MateriaIconography = {
  "arrow-back-rounded": ArrowBackRoundedIcon,
  "arrow-forward-rounded": ArrowForwardRoundedIcon,
  "close-rounded": CloseRoundedIcon,
  "menu-rounded": MenuRoundedIcon,
  "check-rounded": CheckRoundedIcon,
  "add-rounded": AddRoundedIcon,
  "chevron-right-rounded": ChevronRightRoundedIcon,
  "info-rounded": InfoRoundedIcon,
  "info-outline-rounded": InfoOutlineRoundedIcon,
  "home-rounded": HomeRoundedIcon,
  "home-outline-rounded": HomeOutlineRoundedIcon,
  "settings-rounded": SettingsRoundedIcon,
  "settings-outline-rounded": SettingsOutlineRoundedIcon,
  "error-rounded": ErrorRoundedIcon,
  "delete-rounded": DeleteRoundedIcon,
  "light-mode-rounded": LightModeRoundedIcon,
  "dark-mode-rounded": DarkModeRoundedIcon,
  "content-copy-outline-rounded": ContentCopyOutlineRoundedIcon,
};
